name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Trunk
        uses: taiki-e/install-action@v2
        with:
          tool: trunk

      - name: Install Tailwind CSS
        run: npm install tailwindcss

      - name: Install Tailwind CSS CLI
        run: npm install -g @tailwindcss/cli

      - name: Build CSS
        run: npx tailwindcss -o ./tailwind.css

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: src-tauri
          args: --config tauri.conf.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            target/release/*.exe
