name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Trunk
        uses: taiki-e/install-action@v2
        with:
          tool: trunk

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: ""

      - name: Install Tailwind CSS
        run: npm install tailwindcss

      - name: Install Tailwind CSS CLI
        run: npm install -g @tailwindcss/cli

      - name: Build CSS
        run: npx tailwindcss -o ./tailwind.css

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --config src-tauri/tauri.conf.json

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/*.exe
          draft: true
          prerelease: false
          generate_release_notes: true
